export const MAIN_VIEWER_HEIGHT = '700px';
export const MAIN_VIEWER_PANEL_DEFAULT_SIZE_IMG = 50;
export const MAIN_VIEWER_PANEL_MIN_SIZE_IMG = 10;
export const MAIN_VIEWER_PANEL_DEFAULT_SIZE_SVG = 50;
export const MAIN_VIEWER_PANEL_MIN_SIZE_SVG = 10;
